# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_publication_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
