# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161218_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
