# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuartium', '0002_auto_20161226_2016'),
    ]

    operations = [
    ]
